sonar.projectKey=paradigm_serviceparadigm
sonar.projectName=ServiceParadigm.com
sonar.projectVersion=1.0

sonar.sources=src/
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.ts,**/*.spec.ts

sonar.host.url=http://127.0.0.1:9100
sonar.token=

sonar.sourceEncoding=UTF-8
