name = "serviceparadigm-com"
main = "src/worker.ts"
compatibility_date = "2026-06-12"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

# Static assets from Astro build
pages_build_output_dir = "./dist"

# Route the custom domain
routes = [
  { pattern = "serviceparadigm.com", zone_id = "473ebebb4b53769217fa9f7767b8d423" },
  { pattern = "serviceparadigm.com/*", zone_id = "473ebebb4b53769217fa9f7767b8d423" },
  { pattern = "www.serviceparadigm.com/*", zone_id = "473ebebb4b53769217fa9f7767b8d423" }
]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "serviceparadigm-db"
database_id = "22fafb86-b121-4f90-a763-2cd58412ef22"

# R2 bucket for CMS asset uploads
[[r2_buckets]]
binding = "CMS_ASSETS"
bucket_name = "paradigm-cms-assets"

# Environment variables
[vars]
ENVIRONMENT = "production"
PUBLIC_GROWTHBOOK_API_HOST = "http://127.0.0.1:3102"
PUBLIC_GROWTHBOOK_CLIENT_KEY = "sdk-hU8PnivLdq1F0Af"
FEATURE_ORDER_ENABLED = "false"
CONTACT_EMAIL_TO = "hello@serviceparadigm.com"
